apiVersion: apps/v1

kind: Deployment
metadata:
  name:  test-app-deployment
  labels:
    app:  test-app
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 2
  template:
    metadata:
      labels:
        app:  test-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx-test-app
        image: aayushregistry.azurecr.io/test-user-app:889
        resources:
          requests:
            cpu: "0.3"
            memory: 128Mi
          limits:
            cpu: "0.5"
            memory: 256Mi
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  70
          name:  test-user-app
      restartPolicy: Always

      