apiVersion: v1
kind: Service
metadata:
  name: test-user-app-service
spec:
  selector:
    app: test-app
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80